### ISSUE TITLE
Some elimination assignments not registering

### ISSUE THREAD

**Issue by stevegee58** [Shiqan/FortniteReplayDecompressor#40] opened 2022-08-23 16:14 UTC
It seems like the new Kamehameha weapon doesn't register a kill i.e. the player just "dies".
I've attached 2 replay files that show this. In the first game I was #2 and died from the Kamehameha and in the second game I won by eliminating the other player with the Kamehameha.  In both cases the in-game replay says "x killed y" but the kill feed in the replay file doesn't contain a record of this.

[UnsavedReplay-2022.08.20-20.59.33.replay.zip](https://github.com/Shiqan/FortniteReplayDecompressor/files/9404318/UnsavedReplay-2022.08.20-20.59.33.replay.zip)
[UnsavedReplay-2022.08.20-21.21.52.replay.zip](https://github.com/Shiqan/FortniteReplayDecompressor/files/9404322/UnsavedReplay-2022.08.20-21.21.52.replay.zip)

**Comment by Shiqan** [comment] 2022-08-23 18:15
Had a quick look, and the issue is that it simply doesn't add anything to the kill feed.

The following code is responsible for that, and all these properties are null on the final kill.
```csharp
            if (state.RebootCounter > 0 || state.bDBNO != null || state.DeathCause != null || state.DeathLocation != null)
            {
                UpdateKillFeed(channelIndex, playerData, state);
            }
```

I've updated that in the mentioned commit. The killfeed now contains a bunch more kills, I assume those are all Kamehameha  related 🤷‍♂️ 

Let me know if you need it merged.

**Comment by stevegee58** [comment] 2022-08-23 19:24
If you could merge I'd appreciate it!  That way I can just do a git submodule update.
Thanks for your help!

**Closed** 2022-08-27 08:52 UTC
